<?php

/**
 * @file
 * Install, update and uninstall functions for the MobileSearch module.
 */

/**
 * Implements hook_install().
 */
function ding_mobilesearch_install() {
  $types_to_enable = array('ding_event', 'ding_library');
  foreach ($types_to_enable as $type) {
    $key = 'mobilesearch_type__' . $type;
    variable_set($key, TRUE);
    variable_set($key . '__trigger', 'hook_node_insert');
    variable_set($key . '__plugin', 'mobilesearch_rest');
  }
}
